### ISSUE TITLE
IE7, resize does not apply to multiple element with same ID

### ISSUE THREAD

**Issue by ambbone** [adeelejaz/jquery-image-resize#3]
Only the first image with the same ID is resized. In IE8 and FF3, any number of images that share the same ID are resized.

WORKS
    $(function() {
      $( ".resizeme" ).aeImageResize({ height: 250, width: 250 });
    });
      <img alt="Resized Sample Image" class="resizeme" height=300 src="sample1.jpg" width=400>
      <img alt="Resized Sample Image" class="resizeme" height=300 src="sample1.jpg" width=400>
      <img alt="Resized Sample Image" class="resizeme" height=300 src="sample1.jpg" width=400>

DOES NOT WORK
    $(function() {
      $( "#resizeme" ).aeImageResize({ height: 250, width: 250 });
    });
      <img alt="Resized Sample Image" id="resizeme" height=300 src="sample1.jpg" width=400>
      <img alt="Resized Sample Image" id="resizeme" height=300 src="sample1.jpg" width=400>
      <img alt="Resized Sample Image" id="resizeme" height=300 src="sample1.jpg" width=400>

**Comment by adeelejaz** [comment]
W3C defines ID as: "The id attribute specifies its element's unique identifier (ID). The value must be unique amongst all the IDs in the element's [..]"
(Source: http://www.w3.org/TR/html5/elements.html#the-id-attribute)

You use IDs when there is only one occurence per page. Classes are to be used when there are one or more occurences per page.

This is the reason <del>jQuery</del> <ins>IE7</ins> stops after the first resize because when you use ID, its meant to have just one occurence.
